services:
    app:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    queue:
        image: sail-8.3/app
        depends_on:
            - redis
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        command: 'php /var/www/html/artisan queue:work'
    fetch-candles:
        image: sail-8.3/app
        depends_on:
            - redis
            - queue
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            SYMBOL: '${SYMBOL}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        command: 'php /var/www/html/artisan broker:fetch-candles ${SYMBOL}'
        restart: on-failure
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 5

networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
